#!/bin/bash
# Build MeetingScribe.app — a double-clickable macOS launcher (Dock/Spotlight,
# no Terminal). The launcher starts the Flask server in the background if it
# is not already running, then opens the web UI in the default browser.
#
# Usage:  bash tools/make_mac_app.sh
# Installs to /Applications (falls back to ~/Applications).
set -e
PROJECT="$(cd "$(dirname "$0")/.." && pwd)"
PY="$HOME/.meetingscribe/venv/bin/python"
PORT=$("$PY" -c "from config import load_config; print(load_config().get('port', 5005))" 2>/dev/null || echo 5005)

DEST="/Applications/MeetingScribe.app"
if ! mkdir -p "$DEST/Contents" 2>/dev/null; then
    DEST="$HOME/Applications/MeetingScribe.app"
    mkdir -p "$DEST/Contents"
fi
mkdir -p "$DEST/Contents/MacOS" "$DEST/Contents/Resources"

# ----------------------------------------------------------- launcher binary
cat > "$DEST/Contents/MacOS/MeetingScribe" <<LAUNCHER
#!/bin/bash
# MeetingScribe launcher (generated by tools/make_mac_app.sh)
PROJECT="$PROJECT"
PY="\$HOME/.meetingscribe/venv/bin/python"
PORT=$PORT
URL="http://127.0.0.1:\$PORT"

if [ ! -x "\$PY" ]; then
    osascript -e 'display alert "MeetingScribe is not set up yet" message "Open Terminal in the MeetingScribe folder and run:  bash setup.sh" as critical'
    exit 1
fi
if [ ! -f "\$PROJECT/app.py" ]; then
    osascript -e 'display alert "MeetingScribe folder not found" message "The folder this app was built from has moved. Re-run:  bash tools/make_mac_app.sh" as critical'
    exit 1
fi

if ! curl -s -m 1 "\$URL/api/status" >/dev/null 2>&1; then
    cd "\$PROJECT"
    MEETINGSCRIBE_NO_BROWSER=1 nohup "\$PY" app.py >> "\$HOME/.meetingscribe/app.log" 2>&1 &
    for _ in \$(seq 1 120); do
        curl -s -m 1 "\$URL/api/status" >/dev/null 2>&1 && break
        sleep 0.5
    done
fi
open "\$URL"
LAUNCHER
chmod +x "$DEST/Contents/MacOS/MeetingScribe"

# ------------------------------------------------------------------ metadata
cat > "$DEST/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key><string>MeetingScribe</string>
	<key>CFBundleDisplayName</key><string>MeetingScribe</string>
	<key>CFBundleIdentifier</key><string>com.meetingscribe.app</string>
	<key>CFBundleVersion</key><string>1.0</string>
	<key>CFBundleShortVersionString</key><string>1.0</string>
	<key>CFBundlePackageType</key><string>APPL</string>
	<key>CFBundleExecutable</key><string>MeetingScribe</string>
	<key>CFBundleIconFile</key><string>MeetingScribe</string>
	<key>LSMinimumSystemVersion</key><string>11.0</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>MeetingScribe records your microphone during meetings so it can transcribe who said what.</string>
	<key>NSCalendarsFullAccessUsageDescription</key>
	<string>MeetingScribe reads today's calendar events to name your recordings after the meeting you're in.</string>
	<key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------------- icon
"$PY" "$PROJECT/tools/make_icon.py" "$DEST/Contents/Resources/MeetingScribe.icns"

touch "$DEST"  # nudge Finder/LaunchServices to refresh the icon
echo "Installed: $DEST"
echo "Launch it from Spotlight (⌘-space, type MeetingScribe), or drag it to the Dock."
