#!/usr/bin/env python3
"""Regression tests for the mic-only fallback — the thing that broke this week.

WHAT THIS GUARDS
----------------
When an online meeting's system (call-audio) track comes back empty, both sides
of the call were recorded on the microphone, so pipeline clusters the MIC like a
room mic instead of labelling all of it "You". Two independent decisions have to
be right, and both were wrong at some point this week:

  1. _system_track_lost()          — did the system track really record nothing?
     The defect: judging it by a RATIO (system speech ÷ mic speech) instead of an
     ABSOLUTE zero. Every real 1:1 call in the corpus has a system track that is
     quieter than the mic; a ratio gate fires on meetings whose call audio was
     captured perfectly and hands them to the fallback.

  2. _mic_holds_a_second_voice()   — was anybody else actually on that mic?
     The defect: using "the clustering returned more than one cluster" as the
     test. Solo mic tracks split into 2-3 clusters routinely, so under a
     cluster-count test the valve never closes and the user loses their "You"
     label on a meeting that was never broken.

TWO CORPORA
-----------
test/synthetic/   THE BASELINE. Committed, privacy-free, and generated by
                  tools/make_synthetic_fixtures.py from a fixed seed — no audio
                  and no real recording is involved. Every fixture ships a
                  labels.json stating the TRUE number of voices on each track,
                  which is the thing the private corpus cannot provide. This
                  corpus always runs, so the suite works on a clean clone.

test/fixtures/    OPTIONAL, deeper, LOCAL ONLY. Frozen caches of real meetings;
                  gitignored because the titles carry participants' names and
                  analysis.npz holds their ECAPA voice embeddings. It ships no
                  labels, but tools/eval_diarization.py carries a reviewed TRUTH
                  table for 21 of its 22 meetings, and the rows below are read
                  from it. When the corpus is absent every check simply runs on
                  synthetic alone and says so.

                  THIS FILE NAMES NONE OF THOSE MEETINGS. Every local fixture is
                  referred to by the stable pseudonym from
                  docs/DIARIZATION_AUDIT_ADDENDUM.md §0 (Call A..N, Demo, E2E,
                  Room P..W) — in the truth table, in the fixtures singled out by
                  hand, and in everything printed. The pseudonym -> directory map
                  is the de-anonymisation key, so it lives with the data it
                  describes in the gitignored test/fixtures/index.json and is
                  read at runtime; without it the local corpus is simply
                  unavailable, which is the normal state on a clean clone.

EXPECTATIONS COME FROM GROUND TRUTH, NOT FROM THE CODE
------------------------------------------------------
Every number this file asserts about the clustering is derived from how many
people were really on the track — never re-recorded from what the clustering
happens to output today. A table that is re-recorded whenever the fold rule
changes can only agree with the fold rule, which is the one thing it must be
able to disagree with. See the Row class and the table comment for the contract,
including how a case the code cannot currently get right is recorded without
turning the table back into a mirror.

Every check runs against every corpus that is present. Nothing here reads audio,
transcribes, downloads a model, or touches the network; recordings/ and
~/.meetingscribe/ are never opened, and every fixture is copied into a temp dir
before anything that writes runs.

    ~/.meetingscribe/venv/bin/python tools/test_diarization.py

Check functions are named check_* and all work is behind __main__, so a stray
`pytest tools/` collects and runs nothing.
"""

import contextlib
import copy
import json
import shutil
import sys
import tempfile
from collections import Counter
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import diarization as diarization_mod  # noqa: E402
import pipeline  # noqa: E402

# The local corpus ships no labels.json, but tools/eval_diarization.py carries a
# reviewed TRUTH table for 21 of its 22 meetings (how many voices are really on
# the CLUSTERED track, with a tier saying how the number was established). That
# is the only ground truth the real corpus has, so the local rows below are read
# from it rather than invented here, and the two are cross-checked so the unit
# test and the eval harness can never quietly disagree about the same meeting.
sys.path.insert(0, str(REPO / "tools"))
try:
    import eval_diarization as eval_mod  # noqa: E402
except Exception:  # pragma: no cover - the harness is optional, like the corpus
    eval_mod = None

SYNTHETIC_ROOT = REPO / "test" / "synthetic"
LOCAL_ROOT = REPO / "test" / "fixtures"
THRESHOLD = 0.6  # config default; the corpus gates below were measured at it


# ---------------------------------------------------------------------------
# WHAT A ROW SAYS, AND WHY IT IS NOT A RECORDING OF THE CODE
#
# The previous version of this table stored the auto cluster count and the
# detector's verdict as MEASURED NUMBERS, re-recorded whenever the clustering
# changed. That is a mirror, not a test: after the second re-recording it can
# only ever agree with whatever _fold_weak_clusters does today, so it cannot
# catch the very defect it exists for (a real participant folded away, or a
# phantom promoted to a speaker).
#
# So a row states GROUND TRUTH — how many people are really on that mic track —
# and the expectations are derived from it:
#
#     expected cluster count  ==  truth
#     expected verdict        ==  (truth > 1)
#
# Ground truth is never written here by hand. Synthetic rows come from the
# fixture's own labels.json (generated with the voices, so it is construction
# truth, not opinion); local rows come from the reviewed TRUTH table in
# tools/eval_diarization.py. check_the_table_is_grounded_in_truth re-reads both
# every run, so a row that quietly acquires a comfortable "truth" fails.
#
# A row may also record ONE documented miss — a second accepted answer for a
# case the code is known to get wrong and cannot currently get right. Truth and
# the recorded miss both pass; ANYTHING ELSE FAILS. That is what keeps the table
# honest in both directions:
#   * a change that moves a row off truth (or off its recorded miss) onto some
#     third answer is a regression and goes red;
#   * a change that moves a recorded miss ONTO the truth is reported as
#     IMPROVED, stays green, and the miss line can be deleted.
#
# measured 2026-07-25, threshold 0.6, detector gates ratio>=0.25, frag<=0.30
#
#   fixture                  truth  auto  ratio   frag   verdict
#   solo-one-voice               1     1    n/a    n/a   you      correct
#   same-voice-drift             1     1    n/a    n/a   you      correct
#   same-voice-split             1     1    n/a    n/a   you      correct
#   same-voice-big-split         1     1    n/a    n/a   you      correct
#   ask-demo-call                1     1    n/a    n/a   you      correct
#   two-long-turns               2     2  1.000  0.100   second   correct
#   two-medium-turns             2     2  1.000  0.250   second   correct
#   two-rapid-alternation        2     2  1.000  0.333   you      *** MISS ***
#   two-backchannel              2     1    n/a    n/a   you      *** MISS ***
#   three-voices                 3     3  1.000  0.167   second   correct
#   four-voices                  4     4  1.000  0.200   second   correct
#
# THE TWO MISSES ARE THE POINT OF THIS CORPUS, and they are different failures:
#
#   two-rapid-alternation — the CLUSTERING is right (2 clusters, one per voice,
#     every window correctly assigned) and the DETECTOR's gate is wrong.
#     Fragmentation is essentially 1/(turn_length - 1) for an alternating
#     conversation, so pipeline.MIC_ONLY_MAX_FRAGMENTATION = 0.30 is really a
#     rule about how fast people take turns, not about who is speaking:
#
#       genuine 2 speakers, 11 s turns -> 0.100   same voice, scattered -> 0.778
#       genuine 2 speakers,  5 s turns -> 0.250   same voice, large lobe -> 0.714
#       genuine 2 speakers,  3 s turns -> 0.333
#
#     The bands OVERLAP; docs/COUNT_ESTIMATION_DESIGN.md read them as separable
#     from long-turn meetings only, and the separation closes below roughly a
#     five-second turn.
#
#   two-backchannel — the CLUSTERING is wrong: _fold_weak_clusters folds the
#     genuine second person away, so the detector never gets a runner-up to
#     judge. diarization.py names this same fixture as its one measured loss and
#     says separating it needs a speaker-verification score, not another
#     threshold. If the absolute size ceiling being added to the fold rule
#     rescues it, this row goes IMPROVED and its miss line comes out.
# ---------------------------------------------------------------------------


class Row:
    """One cached mic track: what is TRUE about it, plus any documented miss.

    truth          voices really on that track, or None when it cannot be
                   established from the fixture at all.
    at_least       lower bound, used ONLY where truth is None: a weaker claim
                   that is still evidence, so an unknowable row asserts
                   something instead of asserting nothing.
    miss_clusters  a second accepted cluster count (see the table comment).
    miss_verdict   a second accepted _mic_holds_a_second_voice verdict.
    why            what this row is in the corpus to prove.
    """

    def __init__(self, truth=None, why="", at_least=None,
                 miss_clusters=None, miss_verdict=None):
        if truth is None and at_least is None:
            raise ValueError("a row with no truth needs an at_least bound")
        self.truth = truth
        self.at_least = at_least
        self.miss_clusters = miss_clusters
        self.miss_verdict = miss_verdict
        self.why = why

    @property
    def wants_second_voice(self):
        """What ground truth says the mic-only detector should answer."""
        return (self.truth if self.truth is not None else self.at_least) > 1

    def rate_clusters(self, n):
        """'ok' (matches truth), 'miss' (the documented one), or 'bad'."""
        if self.truth is None:
            return "ok" if n >= self.at_least else "bad"
        if n == self.truth:
            return "ok"
        if self.miss_clusters is not None and n == self.miss_clusters:
            return "miss"
        return "bad"

    def rate_verdict(self, got):
        if got == self.wants_second_voice:
            return "ok"
        if self.miss_verdict is not None and got == self.miss_verdict:
            return "miss"
        return "bad"


SYNTHETIC_MIC_ROWS = {
    "synthetic-solo-one-voice-20200101-000001": Row(
        truth=1, why="one voice, one cluster — the trivial control"),
    "synthetic-same-voice-drift-20200101-000007": Row(
        truth=1, why="one voice drifting 80 degrees; the merge puts it back together"),
    "synthetic-same-voice-split-20200101-000008": Row(
        truth=1, why="one voice; the raw clustering splits it and the fold repairs it"),
    "synthetic-same-voice-big-split-20200101-000015": Row(
        truth=1, why="same, with a lobe too big for a duration-only test to reject"),
    "synthetic-ask-demo-call-20200101-000020": Row(
        truth=1, why="the citation fixture's mic track — only the local voice is on it"),
    "synthetic-two-long-turns-20200101-000002": Row(
        truth=2, why="two real voices, long turns"),
    "synthetic-two-medium-turns-20200101-000009": Row(
        truth=2, why="two real voices, five-second turns"),
    "synthetic-two-rapid-alternation-20200101-000003": Row(
        truth=2, miss_verdict=False,
        why="two real voices at ~3 s a turn: clustered correctly, then read as "
            "one because fragmentation 0.333 is over the detector's 0.30 gate"),
    "synthetic-two-backchannel-20200101-000004": Row(
        truth=2, miss_clusters=1, miss_verdict=False,
        why="a real second person who only ever backchannels: the fold deletes "
            "the cluster, so nothing is left for the detector to judge"),
    "synthetic-three-voices-20200101-000005": Row(
        truth=3, why="three real voices"),
    "synthetic-four-voices-20200101-000006": Row(
        truth=4, why="four real voices — must not collapse"),
}

# ---------------------------------------------------------------------------
# LOCAL (optional corpus). Same contract, with truth read from the reviewed
# TRUTH table in tools/eval_diarization.py — for a MIC track that count is every
# voice the mic heard, the local user included (the "total" basis).
#
# KEYED BY PSEUDONYM, NEVER BY DIRECTORY. The local fixtures are real meetings
# and their directory names are the meeting titles: participants' names, their
# employers, and as a set the owner's whole calendar. This file is committed, so
# it names none of them. Every row below, and every fixture this file singles
# out by hand, is identified by the stable label from
# docs/DIARIZATION_AUDIT_ADDENDUM.md §0, exactly as tools/eval_diarization.py
# does; the label -> directory map is read at runtime from the gitignored
# test/fixtures/index.json (see Corpus.resolve). No map, no local corpus — a
# clean clone has none and runs on test/synthetic/ alone.
#
#   pseudonym  what it is                       truth  auto  ratio  frag verdict
#   Room P     1:1 call on speaker                 2     2   0.337 0.139 second
#   Room Q     1:1 call on speaker, 27 min         2     2   0.328 0.148 second
#   Room T     two people in the room, 104 s       2     2   0.918 0.156 second
#   Room R     solo rehearsal, 22 min              1     1    n/a   n/a  you
#   Room S     solo rehearsal, 11 min              1     1    n/a   n/a  you
#   Room U     solo rehearsal, 20 min              1     1    n/a   n/a  you
#   Room V     solo rehearsal, 17 min              1     1    n/a   n/a  you
#   Room W     open floor, 111 min                 ?     7   0.963 0.028 second
#
# Room W is the one meeting in the whole corpus with no establishable count —
# no roster, voices drifting in and out — so it asserts the bound that IS
# established by what the recording is (an open floor with several people
# talking): at least two voices, therefore at least two clusters and a
# second-voice verdict. Pinning its 7 would be pinning the clusterer's opinion,
# which is exactly what eval_diarization.py refuses to call truth.
# ---------------------------------------------------------------------------
LOCAL_MIC_ROWS = {
    "Room P": Row(
        truth=2, why="1:1 call held on speaker: you and the caller, both on the mic"),
    "Room Q": Row(
        truth=2, why="1:1 call held on speaker: you and the caller, both on the mic"),
    "Room R": Row(
        truth=1, why="solo rehearsal — the mic must keep its 'You' label"),
    "Room S": Row(
        truth=1, why="solo rehearsal — the mic must keep its 'You' label"),
    "Room T": Row(
        truth=2, why="two people in the room trading turns throughout"),
    "Room U": Row(
        truth=1, why="solo monologue — the mic must keep its 'You' label"),
    "Room V": Row(
        truth=1, why="solo monologue — the mic must keep its 'You' label"),
    "Room W": Row(
        truth=None, at_least=2,
        why="open floor: the exact count is unknowable, but that it "
            "holds more than one voice is not"),
}


class Corpus:
    """One directory of frozen fixtures plus the ground truth about it.

    Fixtures are addressed by KEY. For the synthetic corpus a key is the
    fixture's own slug, which names nobody. For the local corpus a key is the
    pseudonym, and the key -> directory mapping is read from that corpus's own
    gitignored index (resolve() below) so this file never contains one.
    """

    def __init__(self, name, root, mic_rows, solo_mic, multi_mic,
                 quiet_system, min_online, ask_demo, description,
                 pseudonymous=False):
        self.name = name
        self.root = root
        self.mic_rows = mic_rows
        self.solo_mic = solo_mic
        self.multi_mic = multi_mic
        self.quiet_system = quiet_system
        self.min_online = min_online
        self.ask_demo = ask_demo
        self.description = description
        self.pseudonymous = pseudonymous
        self._slug_by_key = {}
        self._key_by_slug = {}
        self._resolve_problem = ""

    def __repr__(self):
        return f"<corpus {self.name}>"

    def resolve(self):
        """Load the key -> directory map. Returns "" or a reason it is absent.

        Only a pseudonymous corpus needs one: for the synthetic corpus the key
        IS the directory. tools/eval_diarization.py owns the reader, so the unit
        test and the eval harness cannot disagree about which meeting a label
        names.
        """
        if not self.pseudonymous:
            return ""
        self._slug_by_key, self._key_by_slug = {}, {}
        if eval_mod is None:
            self._resolve_problem = (
                "tools/eval_diarization.py could not be imported, so the "
                "pseudonym -> fixture map cannot be read")
            return self._resolve_problem
        mapping, why_not = eval_mod.load_label_map(self.root)
        if not mapping:
            self._resolve_problem = why_not
            return why_not
        self._slug_by_key = dict(mapping)
        self._key_by_slug = {v: k for k, v in mapping.items()}
        self._resolve_problem = ""
        return ""

    @property
    def resolve_problem(self):
        """Why this corpus cannot be addressed, or "" — set by resolve()."""
        return self._resolve_problem

    def slug_for(self, key):
        """The directory a key names. Unmapped keys pass through unchanged."""
        return self._slug_by_key.get(key, key)

    def key_for(self, slug):
        """The pseudonym a directory is known by. Unmapped ones pass through."""
        return self._key_by_slug.get(slug, slug)

    @property
    def present(self):
        if not (self.root.is_dir() and any(self.root.glob("*/meeting.json"))):
            return False
        return not self.resolve()

    def dirs(self):
        return sorted(p for p in self.root.iterdir()
                      if p.is_dir() and (p / "meeting.json").exists())

    def keys(self):
        """Every fixture present on disk, named the way this file names it."""
        return sorted(self.key_for(d.name) for d in self.dirs())


SYNTHETIC = Corpus(
    name="synthetic",
    root=SYNTHETIC_ROOT,
    mic_rows=SYNTHETIC_MIC_ROWS,
    # One voice that the RAW clustering splits in two: the fold has to put it
    # back together and the detector has to keep the "You" label.
    solo_mic="synthetic-same-voice-split-20200101-000008",
    multi_mic="synthetic-two-long-turns-20200101-000002",
    quiet_system="synthetic-call-quiet-far-end-20200101-000014",
    min_online=6,
    ask_demo="synthetic-ask-demo-call-20200101-000020",
    description="committed, generated by tools/make_synthetic_fixtures.py",
)

LOCAL = Corpus(
    name="local",
    root=LOCAL_ROOT,
    mic_rows=LOCAL_MIC_ROWS,
    solo_mic="Room V",   # 927 windows, one voice
    multi_mic="Room T",  # 68 windows, several
    # A real 1:1 online call whose system track recorded fine. The fallback must
    # never fire on it, however much quieter the far end is than the mic.
    quiet_system="Call L",
    min_online=8,
    ask_demo="Demo",
    description="local only, gitignored, derived from real recordings",
    pseudonymous=True,
)


def skip_note():
    """Why the local corpus is not running. Never names a fixture."""
    if not LOCAL_ROOT.is_dir():
        reason = f"{LOCAL_ROOT} does not exist."
    elif not any(LOCAL_ROOT.glob("*/meeting.json")):
        reason = f"{LOCAL_ROOT} holds no frozen fixtures."
    else:
        reason = LOCAL.resolve_problem or "unknown."
    return (
        "SKIPPED the optional local corpus. It is gitignored on purpose (real "
        "participants' voice embeddings, and directory names that are real "
        "meeting titles), so this is the normal state on a clean clone, and the "
        "committed synthetic corpus covers every check below.\n"
        f"  reason: {reason}"
    )


# Kept as a module attribute because the sibling suites print it.
SKIP_NOTE = (
    "SKIPPED the optional local corpus: it is gitignored on purpose (real "
    "participants' voice embeddings and names), so this is the normal state on "
    "a clean clone. The committed synthetic corpus covers every check below."
)


def corpora():
    """Every corpus to run against. Synthetic is mandatory, local is a bonus."""
    if not SYNTHETIC.present:
        raise SystemExit(
            f"the committed synthetic corpus is missing from {SYNTHETIC_ROOT} — "
            "regenerate it with\n"
            "    ~/.meetingscribe/venv/bin/python tools/make_synthetic_fixtures.py"
        )
    return [SYNTHETIC] + ([LOCAL] if LOCAL.present else [])


# ------------------------------------------------------------------ fixtures --

def fixture_dir(corpus, key):
    """The directory a KEY names — a pseudonym on the local corpus, a slug on
    the synthetic one. A directory name passed straight in still resolves, so
    the sibling suites that name synthetic fixtures directly keep working."""
    d = corpus.root / corpus.slug_for(key)
    if not d.is_dir():
        raise SystemExit(f"missing fixture {key} under {corpus.root}")
    return d


def load_transcripts(corpus, slug):
    """Deep copy of a fixture's cached transcripts — callers mutate them."""
    path = fixture_dir(corpus, slug) / "analysis.json"
    return copy.deepcopy(json.loads(path.read_text(encoding="utf-8"))["transcripts"])


def load_meta(corpus, slug):
    return json.loads(
        (fixture_dir(corpus, slug) / "meeting.json").read_text(encoding="utf-8"))


def load_labels(corpus, slug):
    """Ground truth, or None for a corpus that has none (the local one)."""
    path = fixture_dir(corpus, slug) / "labels.json"
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def load_precomputed(corpus, slug):
    """{track: (windows, embeddings)} straight from the frozen npz."""
    out = {}
    npz_path = fixture_dir(corpus, slug) / "analysis.npz"
    if not npz_path.exists():
        return out
    with np.load(npz_path) as npz:
        for key in npz.files:
            if not key.endswith("_embeddings"):
                continue
            track = key[: -len("_embeddings")]
            wkey = f"{track}_windows"
            if wkey in npz.files:
                out[track] = (np.array(npz[wkey]), np.array(npz[key]))
    return out


def has_mic_embeddings(corpus, slug):
    """True when the fixture carries a cached mic track, without loading it."""
    npz_path = fixture_dir(corpus, slug) / "analysis.npz"
    if not npz_path.exists():
        return False
    with np.load(npz_path) as npz:
        return "mic_embeddings" in npz.files and "mic_windows" in npz.files


def mic_state(corpus, slug):
    """The {"windows", "embeddings"} dict _mic_holds_a_second_voice expects."""
    pre = load_precomputed(corpus, slug)
    if "mic" not in pre:
        raise SystemExit(f"fixture {slug} has no cached mic embeddings")
    windows, embeddings = pre["mic"]
    return {
        "windows": [tuple(w) for w in np.asarray(windows).tolist()],
        "embeddings": np.asarray(embeddings, dtype=np.float64),
    }


# Clustering Room W's 4594-window track is the slowest thing in this file
# and three checks want the same labels, so each (fixture, folded?) pair is
# computed once. Deterministic input, deterministic clustering, so caching
# changes nothing but the runtime.
_LABEL_CACHE = {}


def mic_labels(corpus, slug, state=None, folded=True):
    """Per-window cluster labels for a mic track.

    folded=True is the auto path the app runs: cluster() is handed durations, so
    _fold_weak_clusters gets to repair same-voice splits. It is the identical
    call pipeline._mic_holds_a_second_voice makes internally.

    folded=False passes no durations, which skips the fold entirely. That is the
    RAW clustering — what the threshold and the k-ceiling produce before any
    repair — and it is how the checks below can talk about phantom over-splits
    without depending on how aggressive today's fold rule happens to be.
    """
    key = (corpus.name, slug, folded)
    if key not in _LABEL_CACHE:
        state = state or mic_state(corpus, slug)
        durations = ([w[1] - w[0] for w in state["windows"]] if folded else None)
        _LABEL_CACHE[key] = list(pipeline.diarization.cluster(
            state["embeddings"], n_speakers=None, threshold=THRESHOLD,
            durations=durations,
        ))
    return _LABEL_CACHE[key]


def cluster_purity(labels, true_voices):
    """Share of windows sitting in a cluster their own voice dominates.

    1.0 means no cluster mixes two real people. It is the half of correctness a
    cluster COUNT cannot see: three voices split into three clusters that each
    hold a bit of everyone scores 3 == 3 on the count and 0.33 here.
    """
    total = 0
    for lab in set(labels):
        seen = Counter(v for l, v in zip(labels, true_voices) if l == lab)
        total += max(seen.values())
    return total / float(len(true_voices))


def _num(x):
    """Format a measurement that may legitimately be absent (one cluster)."""
    return "  n/a" if x is None else f"{x:.3f}"


@contextlib.contextmanager
def recluster_workdir(corpus, slug):
    """A temp copy of a fixture, rewritten as an online call with no call audio.

    Yields the directory. recluster_meeting() writes meeting.json (and possibly
    analysis.*) into it, so it must never be the fixture itself.
    """
    with tempfile.TemporaryDirectory(prefix="ms-recluster-test-") as tmp:
        work = Path(tmp) / slug
        shutil.copytree(fixture_dir(corpus, slug), work)

        meta_path = work / "meeting.json"
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        meta["mode"] = "online"
        for key in ("diarization_mode", "speaker_count_source",
                    "speaker_count_basis"):
            meta.pop(key, None)
        meta_path.write_text(json.dumps(meta), encoding="utf-8")

        analysis_path = work / "analysis.json"
        analysis = json.loads(analysis_path.read_text(encoding="utf-8"))
        analysis["transcripts"]["system"] = []  # the silent call-audio track
        analysis_path.write_text(json.dumps(analysis), encoding="utf-8")

        yield work


def label_as_online_mic_only(corpus, slug, expected=None, meta_overrides=None):
    """Run pipeline's labelling step over a fixture presented as a mic-only call.

    Returns (meta, warnings). The fixture is copied to a temp dir first, so the
    corpus is never written to even if the pipeline changes to write.
    """
    with tempfile.TemporaryDirectory(prefix="ms-diar-test-") as tmp:
        work = Path(tmp) / slug
        shutil.copytree(fixture_dir(corpus, slug), work)

        meta = load_meta(corpus, slug)
        meta["mode"] = "online"
        meta.pop("diarization_mode", None)
        meta.pop("speaker_count_source", None)
        meta.pop("speaker_count_basis", None)
        meta.update(meta_overrides or {})

        transcripts = load_transcripts(corpus, slug)
        transcripts["system"] = []  # the silent call-audio track

        warnings = pipeline._label_and_assemble(
            work, meta, transcripts, pipeline.load_config(), expected,
            lambda msg: None, precomputed=load_precomputed(corpus, slug),
            collect={},
        )
    return meta, warnings


# -------------------------------------------------------------------- checks --

def check_corpus_is_usable(fail, corpus):
    """The fixtures are readable, and the synthetic ones are still current.

    A synthetic cache stamped with a different diarization.EMBED_VERSION would
    be silently rejected by _load_analysis_cache, and every check below would
    fall through to embedding real audio that does not exist. Better to say so.
    """
    dirs = corpus.dirs()
    print(f"    {len(dirs)} fixture(s) in {corpus.root.name}/ ({corpus.description})")
    if not dirs:
        fail(f"{corpus.name}: no fixtures under {corpus.root}")
        return

    missing = [k for k in corpus.mic_rows
               if not (corpus.root / corpus.slug_for(k)).is_dir()]
    if missing:
        fail(f"the truth table names fixtures that are not in the corpus: {missing}")

    # And the other direction: a mic track nobody has an opinion about is a mic
    # track this file silently does not test. Adding a fixture must force a row.
    uncovered = [corpus.key_for(d.name) for d in dirs
                 if corpus.key_for(d.name) not in corpus.mic_rows
                 and has_mic_embeddings(corpus, d.name)]
    if uncovered:
        fail(f"{corpus.name}: these fixtures have cached mic embeddings but no "
             f"row in the table, so nothing checks them: {uncovered}")

    if corpus is not SYNTHETIC:
        return

    index = json.loads((corpus.root / "index.json").read_text(encoding="utf-8"))
    stamped = index.get("embed_version")
    print(f"    embed_version stamped {stamped}, code is "
          f"{diarization_mod.EMBED_VERSION}")
    if stamped != diarization_mod.EMBED_VERSION:
        fail(f"the committed synthetic fixtures were stamped embed_version "
             f"{stamped} but diarization.EMBED_VERSION is now "
             f"{diarization_mod.EMBED_VERSION}, so the pipeline would reject "
             "every cached embedding and try to read audio that does not "
             "exist. Regenerate them:\n"
             "    ~/.meetingscribe/venv/bin/python tools/make_synthetic_fixtures.py")


def check_the_table_is_grounded_in_truth(fail, corpus):
    """Every "truth" in the table must come from the data, not from this file.

    Without this the table is just prose: somebody could record a comfortable
    truth next to an uncomfortable verdict and nothing would notice. Synthetic
    truth is checked against the fixture's own labels.json — including its
    per-window labels, so an inconsistent fixture is caught too — and local
    truth against the reviewed table in tools/eval_diarization.py.
    """
    rows = corpus.mic_rows
    if corpus is SYNTHETIC:
        for slug, row in sorted(rows.items()):
            labels = load_labels(corpus, slug)
            if labels is None:
                fail(f"{slug} has no labels.json, so its truth is unverifiable")
                continue
            mic = labels["tracks"]["mic"]
            on_track = len(mic["true_voices"])
            if on_track != row.truth:
                fail(f"{slug}: the table says {row.truth} true voice(s) on the "
                     f"mic, labels.json says {on_track}")
            heard = sorted(set(mic["window_voices"]))
            if heard != sorted(mic["true_voices"]):
                fail(f"{slug}: labels.json declares voices "
                     f"{sorted(mic['true_voices'])} but its per-window labels "
                     f"contain {heard} — the fixture's own truth is inconsistent")
            n_windows = len(mic_state(corpus, slug)["windows"])
            if len(mic["window_voices"]) != n_windows:
                fail(f"{slug}: {len(mic['window_voices'])} per-window labels for "
                     f"{n_windows} cached windows — the labels and the "
                     "embeddings were not generated together")
        print(f"    {len(rows)} rows agree with the fixtures' labels.json "
              "(count, voice set, and one label per cached window)")
        return

    if eval_mod is None:
        fail("tools/eval_diarization.py could not be imported, so the local "
             "rows' truth cannot be checked against the reviewed table")
        return
    for slug, row in sorted(rows.items()):
        count, tier, note = eval_mod.truth_of(slug)
        if count != row.truth:
            fail(f"{slug}: this table says {row.truth} voice(s) on the mic, "
                 f"tools/eval_diarization.py says {count} ({tier}: {note}) — "
                 "the unit test and the eval harness disagree about the same "
                 "meeting, so one of them is scoring against a wrong answer")
        if row.truth is None and tier in ("known", "inferred"):
            fail(f"{slug} is treated here as unknowable, but the eval harness "
                 f"has a {tier} count of {count} — use it")
    known = sum(1 for r in rows.values() if r.truth is not None)
    print(f"    {len(rows)} rows agree with tools/eval_diarization.py's TRUTH "
          f"table ({known} with a count, {len(rows) - known} bounded only)")


def check_system_track_lost_is_absolute(fail, corpus):
    """DEFECT: a ratio gate hands perfectly-recorded calls to the fallback.

    Every online fixture whose system track transcribed anything at all must
    read as NOT lost — including the quietest far end in the corpus, and a track
    cut down to one single segment (a ratio gate sees ~0.005 and fires; an
    absolute gate does not).
    """
    online = []
    for d in corpus.dirs():
        meta = json.loads((d / "meeting.json").read_text(encoding="utf-8"))
        if meta.get("mode") != "online":
            continue
        key = corpus.key_for(d.name)
        tr = load_transcripts(corpus, key)
        mic, sys_segs = tr.get("mic") or [], tr.get("system") or []
        if not mic or not sys_segs:
            continue
        online.append((key, mic, sys_segs))

    if len(online) < corpus.min_online:
        fail(f"{corpus.name}: expected >={corpus.min_online} usable online "
             f"fixtures, got {len(online)}")

    for key, mic, sys_segs in online:
        if pipeline._system_track_lost(mic, sys_segs):
            ratio = (pipeline._speech_seconds(sys_segs)
                     / max(pipeline._speech_seconds(mic), 1e-9))
            fail(f"fallback fired on {key}, whose system track has "
                 f"{pipeline._speech_seconds(sys_segs):.0f}s of speech "
                 f"(system/mic ratio {ratio:.3f})")

    # The extreme: a system track reduced to its single shortest segment.
    match = [s for s in online if s[0] == corpus.quiet_system]
    if not match:
        fail(f"{corpus.name}: the designated quiet-system fixture "
             f"{corpus.quiet_system} is not a usable online fixture")
        return
    _key, mic, sys_segs = match[0]
    sliver = [min(sys_segs, key=lambda s: float(s["end"]) - float(s["start"]))]
    ratio = pipeline._speech_seconds(sliver) / pipeline._speech_seconds(mic)
    if pipeline._system_track_lost(mic, sliver):
        fail(f"fallback fired on a system track holding one real segment "
             f"({pipeline._speech_seconds(sliver):.1f}s, ratio {ratio:.4f}) — "
             "the detector is judging a ratio, not an absolute silence")
    print(f"    quietest single-segment system track: ratio {ratio:.4f} -> not lost")

    # And the true positive it exists for.
    if not pipeline._system_track_lost(mic, []):
        fail("fallback did NOT fire on a genuinely empty system track")

    # ...but not on a mic too short to judge.
    short = [s for s in mic
             if float(s["end"]) <= pipeline.MIC_ONLY_MIN_MIC_S / 2.0]
    if pipeline._speech_seconds(short) >= pipeline.MIC_ONLY_MIN_MIC_S:
        short = short[:1]
    if pipeline._system_track_lost(short, []):
        fail(f"fallback fired on a mic holding only "
             f"{pipeline._speech_seconds(short):.1f}s of speech, under the "
             f"{pipeline.MIC_ONLY_MIN_MIC_S}s floor")

    print(f"    {len(online)} online fixtures with real call audio: none lost")


def check_second_voice_verdicts(fail, corpus):
    """DEFECT: counting clusters as evidence of a second person.

    Table-driven over every cached mic track. Both expectations come from
    ground truth (see the table comment): the auto path must find as many
    clusters as there are people, and the mic-only detector must say "second
    voice" exactly when there is one. A row may also stand on ONE documented
    miss; landing anywhere else is a failure.

    WHAT THIS CATCHES. A real participant folded away by the clustering shows up
    as clusters < truth on the multi-voice rows (that is the "2 people detected
    as 1" bug, and today two-backchannel is sitting in it). A phantom promoted
    to a speaker shows up as clusters > truth on the single-voice rows — the
    solo rehearsals, which split into five to eight raw clusters before the fold
    repairs them, are the fixtures that would catch it.
    """
    misses, improvements = [], []
    for slug in sorted(corpus.mic_rows):
        row = corpus.mic_rows[slug]
        state = mic_state(corpus, slug)
        got, (ratio, frag) = pipeline._mic_holds_a_second_voice(state, THRESHOLD)
        n_clusters = len(set(mic_labels(corpus, slug, state)))

        rated_c = row.rate_clusters(n_clusters)
        rated_v = row.rate_verdict(got)
        worst = ("bad" if "bad" in (rated_c, rated_v)
                 else "miss" if "miss" in (rated_c, rated_v) else "ok")
        mark = {"ok": "ok ", "miss": "MISS", "bad": "BAD "}[worst]
        truth_col = str(row.truth) if row.truth is not None else f">={row.at_least}"
        note = ""
        if worst == "miss":
            note = "   <-- KNOWN MISS vs ground truth"
        elif rated_c == "ok" and row.miss_clusters is not None:
            note = "   <-- IMPROVED: the recorded cluster miss is gone"
        elif rated_v == "ok" and row.miss_verdict is not None:
            note = "   <-- IMPROVED: the recorded verdict miss is gone"
        print(f"    {mark} {slug[:46]:48s} truth={truth_col:>3s} "
              f"clusters={n_clusters} ratio={_num(ratio)} frag={_num(frag)} -> "
              f"{'second voice' if got else 'just you':12s}{note}")

        if rated_c == "bad":
            fail(f"{slug}: the auto path found {n_clusters} cluster(s) on a mic "
                 f"track that really holds {truth_col} voice(s) — {row.why}")
        if rated_v == "bad":
            fail(f"{slug}: mic-only verdict is "
                 f"{'second voice' if got else 'just you'}, ground truth says "
                 f"{'second voice' if row.wants_second_voice else 'just you'} "
                 f"(ratio {_num(ratio)}, fragmentation {_num(frag)}, "
                 f"{n_clusters} clusters) — {row.why}")
        if worst == "miss":
            misses.append((slug, truth_col, n_clusters, ratio, frag))
        if note.startswith("   <-- IMPROVED"):
            improvements.append(slug)

    if misses:
        print(f"    {len(misses)} row(s) stand on a documented miss rather than "
              "on the truth (see the table comment for why each one is there):")
        for slug, truth_col, n_clusters, ratio, frag in misses:
            print(f"      {slug[:52]:54s} {truth_col} real voice(s) -> "
                  f"{n_clusters} cluster(s), ratio {_num(ratio)}, "
                  f"fragmentation {_num(frag)}")
    if improvements:
        print("    THE CODE NOW BEATS THE TABLE on "
              f"{', '.join(s[:52] for s in improvements)} — delete those rows' "
              "miss_clusters/miss_verdict so the improvement is protected.")

    # Unjudgeable input must mean "no", never "yes": no windows, no gamble.
    for bad in (None, {}, {"windows": [], "embeddings": []},
                {"windows": [(0.0, 1.0)], "embeddings": np.zeros((1, 192))}):
        got, _ = pipeline._mic_holds_a_second_voice(bad, THRESHOLD)
        if got:
            fail(f"mic-only verdict was 'second voice' on unjudgeable state {bad!r}")


def check_separation_margin_is_reported(fail, corpus):
    """The design doc asks for the MARGIN, not a pass/fail. Measure and print it.

    docs/COUNT_ESTIMATION_DESIGN.md conditions the whole speaker-count rule on
    "sweep both thresholds and report the separation margin". It needs a known
    true count, which both corpora now have — synthetic from labels.json, local
    from tools/eval_diarization.py's TRUTH table.

    MEASURED ON THE RAW, PRE-FOLD CLUSTERING, and that is the change worth
    understanding. _fold_weak_clusters now repairs every same-voice over-split
    in both corpora, so post-fold there is no phantom runner-up left anywhere to
    measure a margin against, and asking for one just fails. The over-splits are
    still there in the embeddings; the fold removes them. So the populations are
    measured before the fold, which is
      (a) the honest description of what the two signals have to separate, and
      (b) independent of how aggressive today's fold rule is, which is exactly
          the property a test of the fold rule must have.
    It also keeps the negative control alive: as long as a single-voice fixture
    over-splits raw, "more than one cluster" is disproved as a test for a second
    person, whatever the fold happens to do with it afterwards.
    """
    genuine, phantom, survivors = [], [], []
    for slug, row in sorted(corpus.mic_rows.items()):
        if row.truth is None:
            continue  # a bound is not enough to put a row in one population
        state = mic_state(corpus, slug)
        raw = mic_labels(corpus, slug, state, folded=False)
        ratio, frag = pipeline._runner_up_evidence(state["windows"], raw)
        n_auto = len(set(mic_labels(corpus, slug, state)))
        if row.truth == 1 and len(set(raw)) > 1:
            survivors.append((slug, len(set(raw)), n_auto))
        if ratio is None:
            continue  # a single raw cluster has no runner-up to measure
        (genuine if row.truth > 1 else phantom).append((slug, ratio, frag))

    if not genuine or not phantom:
        fail("the corpus no longer contains BOTH a genuine multi-voice mic and "
             "a single-voice mic whose raw clustering over-splits, so nothing "
             "here separates a real second person from a phantom")
        return

    g_frag = [f for _, _, f in genuine]
    p_frag = [f for _, _, f in phantom]
    g_ratio = [r for _, r, _ in genuine]
    p_ratio = [r for _, r, _ in phantom]
    print(f"    fragmentation  genuine {min(g_frag):.3f}-{max(g_frag):.3f}   "
          f"same voice {min(p_frag):.3f}-{max(p_frag):.3f}   "
          f"gate <= {pipeline.MIC_ONLY_MAX_FRAGMENTATION}")
    print(f"    duration ratio genuine {min(g_ratio):.3f}-{max(g_ratio):.3f}   "
          f"same voice {min(p_ratio):.3f}-{max(p_ratio):.3f}   "
          f"gate >= {pipeline.MIC_ONLY_MIN_DURATION_RATIO}")
    frag_margin = min(p_frag) - max(g_frag)
    ratio_margin = min(g_ratio) - max(p_ratio)
    print(f"    separation margin: fragmentation {frag_margin:+.3f}, "
          f"duration ratio {ratio_margin:+.3f} "
          f"({'both signals overlap' if frag_margin <= 0 and ratio_margin <= 0 else 'see above'})")
    print("    NOTE: a negative margin means the two populations OVERLAP on "
          "that signal, so no threshold on it alone can separate them. This is "
          "the measurement docs/COUNT_ESTIMATION_DESIGN.md made mandatory "
          "before its rule is adopted; the doc's 'no overlap' reading came "
          "from long-turn meetings only.")

    print(f"    {len(survivors)} single-voice fixture(s) over-split before the "
          "fold — raw -> auto: "
          + ", ".join(f"{s[:28]} {r}->{a}" for s, r, a in survivors))
    still_split = [s for s, _, a in survivors if a > 1]
    if still_split:
        print(f"    {len(still_split)} of them still reach the detector as more "
              "than one cluster, so the gates above are what stops them")
    else:
        print("    NOTE: none survive the fold, so on this corpus the detector's "
              "gates are never the thing rejecting a phantom — the fold is. The "
              "gates are exercised only in the positive direction here; weaken "
              "the fold and the margin above is what would have to hold.")


def check_no_cluster_mixes_two_real_voices(fail, corpus):
    """Ground truth per WINDOW, not just a total.

    The right number of clusters can still be right for the wrong reason: three
    voices split into three clusters that each hold a bit of everyone scores
    3 == 3 on the count and is useless to the user, who gets three speakers
    whose lines are shuffled. test/synthetic/ ships a true voice label for every
    window, so that failure is checkable rather than merely worried about.

    The bar is 1.000 — no cluster mixing two people at all — which every fixture
    whose count matches truth clears today. A row standing on a documented
    cluster miss is measured against the weaker floor its miss implies: it must
    still beat "put every window in one cluster", so a fold that scrambles
    voices is caught even where a fold that merges them is tolerated.
    """
    if corpus is not SYNTHETIC:
        print("    (needs a true voice label per window — synthetic corpus only)")
        return
    for slug, row in sorted(corpus.mic_rows.items()):
        state = mic_state(corpus, slug)
        labels = mic_labels(corpus, slug, state)
        voices = load_labels(corpus, slug)["tracks"]["mic"]["window_voices"]
        purity = cluster_purity(labels, voices)
        floor = max(Counter(voices).values()) / float(len(voices))
        on_truth = row.rate_clusters(len(set(labels))) == "ok"
        want = 1.0 if on_truth else floor
        ok = purity >= want - 1e-9
        print(f"    {'ok ' if ok else 'BAD'} {slug[:46]:48s} "
              f"{len(set(labels))} cluster(s) over {len(set(voices))} real "
              f"voice(s), purity {purity:.3f} (need {want:.3f})")
        if not ok and on_truth:
            fail(f"{slug}: {len(set(labels))} clusters is the right count but "
                 f"purity is only {purity:.3f} — the clusters are mixing real "
                 "voices, so the speakers shown to the user have each other's "
                 "lines")
        elif not ok:
            fail(f"{slug}: purity {purity:.3f} is below {floor:.3f}, which is "
                 "what putting every window in a single cluster would score — "
                 "the clustering is worse than not clustering at all")


def check_revert_to_you_valve(fail, corpus):
    """A solo mic track keeps "You" end to end, and keeps no fallback marker."""
    meta, warnings = label_as_online_mic_only(corpus, corpus.solo_mic)
    speakers = meta["speakers"]
    print(f"    solo mic  -> speakers={json.dumps(speakers)} "
          f"mode={meta.get('diarization_mode')!r}")
    if speakers != {"you": "You"}:
        fail(f"solo mic track lost its 'You' label: speakers={speakers}")
    if meta.get("diarization_mode") is not None:
        fail("solo mic track was marked diarization_mode="
             f"{meta['diarization_mode']!r}; the marker must be cleared, "
             "never left stale")
    if any(w == pipeline.MIC_ONLY_WARNING for w in warnings):
        fail("solo mic track raised the mic-only warning")


def check_fallback_engages_on_real_room(fail, corpus):
    """A mic that really holds several voices does engage — and names nobody You."""
    meta, warnings = label_as_online_mic_only(corpus, corpus.multi_mic)
    speakers = meta["speakers"]
    print(f"    multi-voice mic -> speakers={json.dumps(speakers)} "
          f"mode={meta.get('diarization_mode')!r}")
    if meta.get("diarization_mode") != "mic_fallback":
        fail(f"multi-voice mic was not marked mic_fallback "
             f"(got {meta.get('diarization_mode')!r})")
    if "you" in speakers:
        fail("under the mic-only fallback no cluster is known to be the local "
             f"user, but a 'you' speaker was emitted: {speakers}")
    if len(speakers) < 2:
        fail(f"mic_fallback engaged but produced {len(speakers)} speaker(s)")
    if pipeline.MIC_ONLY_WARNING not in warnings:
        fail("mic_fallback engaged without telling the user why "
             f"(warnings={warnings})")


def check_calendar_guess_never_forces(fail, corpus):
    """DEFECT: forcing the calendar's invitee count onto the mic.

    expected_speakers arrives from the calendar at record time. Under the
    fallback it says nothing about how many voices reached the mic, and
    cluster(n_speakers=N) returns exactly N clusters unconditionally — so
    honouring a guess manufactures phantom speakers. Only a count a HUMAN
    picked (speaker_count_source == "user") may be honoured.
    """
    meta, _ = label_as_online_mic_only(
        corpus, corpus.solo_mic, expected=5,
        meta_overrides={"expected_speakers": 5},
    )
    print(f"    calendar guess of 5 on a solo mic -> "
          f"speakers={json.dumps(meta['speakers'])}")
    if meta["speakers"] != {"you": "You"}:
        fail("a calendar-derived expected_speakers=5 was force-applied to the "
             f"mic under the fallback: speakers={meta['speakers']}")


def check_user_count_overrides_both_ways(fail, corpus):
    """The escape hatch: a human-picked count wins in both directions.

    1 on a mic the detector called multi-voice puts the meeting back on the
    "You" path; a count > 1 on a solo mic forces that many voices. Both are
    read through _user_speaker_count, which CONTRACT 1 defines in terms of
    speaker_count_basis; the basis is stamped here so this check states the
    override behaviour and not the basis arithmetic (that is test_modes.py).
    """
    total = {"speaker_count_source": pipeline.SPEAKER_COUNT_USER,
             "speaker_count_basis": "total"}

    meta, warnings = label_as_online_mic_only(
        corpus, corpus.multi_mic,
        meta_overrides=dict(total, expected_speakers=1),
    )
    print(f"    user says 1 voice on a multi-voice mic -> "
          f"speakers={json.dumps(meta['speakers'])}")
    if meta["speakers"] != {"you": "You"}:
        fail("user-chosen count of 1 did not put the meeting back on the 'You' "
             f"path: speakers={meta['speakers']}")
    if meta.get("diarization_mode") is not None:
        fail("user-chosen count of 1 left the mic_fallback marker behind")

    meta, _ = label_as_online_mic_only(
        corpus, corpus.solo_mic,
        meta_overrides=dict(total, expected_speakers=3),
    )
    print(f"    user says 3 voices on a solo mic -> "
          f"speakers={json.dumps(meta['speakers'])}")
    if len(meta["speakers"]) != 3:
        fail("a user-chosen count of 3 was not honoured under the fallback: "
             f"speakers={meta['speakers']}")
    if meta.get("diarization_mode") != "mic_fallback":
        fail("a user-chosen count > 1 did not engage the fallback "
             f"(got {meta.get('diarization_mode')!r})")


def check_recluster_writes_the_marker(fail, corpus):
    """End to end through recluster_meeting(): the on-disk meeting.json agrees.

    This is the path the speaker-count dropdown actually takes, and the only
    one that proves the marker survives to the template. Runs on a temp copy.
    """
    with recluster_workdir(corpus, corpus.solo_mic) as work:
        meta_path = work / "meeting.json"
        out = pipeline.recluster_meeting(work, None)
        on_disk = json.loads(meta_path.read_text(encoding="utf-8"))
        print(f"    recluster(None) -> speakers={json.dumps(on_disk['speakers'])} "
              f"status={on_disk['status']!r}")
        if out["speakers"] != on_disk["speakers"]:
            fail("recluster returned a different speaker map than it wrote")
        if on_disk["speakers"] != {"you": "You"}:
            fail(f"recluster lost the 'You' label: {on_disk['speakers']}")
        if "diarization_mode" in on_disk:
            fail("recluster left a stale diarization_mode in meeting.json")
        if any(w == pipeline.MIC_ONLY_WARNING for w in on_disk.get("warnings", [])):
            fail("recluster left the mic-only warning on a solo meeting")


CHECKS = [
    ("the corpus is present and current", check_corpus_is_usable),
    ("the table's truth comes from the fixtures", check_the_table_is_grounded_in_truth),
    ("system-track-lost is absolute, not a ratio", check_system_track_lost_is_absolute),
    ("second-voice verdicts over the mic corpus", check_second_voice_verdicts),
    ("no cluster mixes two real voices", check_no_cluster_mixes_two_real_voices),
    ("separation margin between real and phantom", check_separation_margin_is_reported),
    ("revert-to-You valve keeps 'You' on a solo mic", check_revert_to_you_valve),
    ("fallback engages on a real multi-voice mic", check_fallback_engages_on_real_room),
    ("a calendar guess never forces a count", check_calendar_guess_never_forces),
    ("a user-chosen count overrides both ways", check_user_count_overrides_both_ways),
    ("recluster_meeting writes an honest meeting.json", check_recluster_writes_the_marker),
]


def run(checks, failures):
    """Run `checks` against every present corpus. Shared by the sibling suites."""
    active = corpora()
    print(f"corpora: {', '.join(c.name for c in active)}")
    if LOCAL not in active:
        print(skip_note())
    ran = 0
    for name, fn in checks:
        for corpus in active:
            print(f"\n== [{corpus.name}] {name}")
            before = len(failures)
            try:
                fn(failures.append, corpus)
            except Exception as exc:  # a crash is a failure, not a stack trace
                failures.append(f"[{corpus.name}] {name}: "
                                f"raised {type(exc).__name__}: {exc}")
                import traceback
                traceback.print_exc()
            ran += 1
            print(f"   {'FAIL' if len(failures) > before else 'PASS'}")
    return ran


def report(failures, ran):
    print("\n" + "=" * 72)
    if failures:
        print(f"{len(failures)} FAILURE(S):")
        for f in failures:
            print(f"  - {f}")
        return 1
    print(f"OK — {ran} checks passed.")
    return 0


def main():
    failures = []
    ran = run(CHECKS, failures)
    return report(failures, ran)


if __name__ == "__main__":
    sys.exit(main())
